<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Check Availability'); ?>
<div class="box-tocart">
    <div class="fieldset">
        
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Check Availability at ') ?></span></label>
            <div class="control">
			<p>
             <input type="text"
        			name="checkzipcode" 
					id="checkzipcode"
					value="" 
					class="input-text"
					/>
            <button type="button"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary checkzipcodebutton"
                    id="product-checkzipcode-button"  onclick="checkgivenzipcode();">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
			</p> 
            <div id="ziploder" style="display:none;">
             <img src="http://localhost/magento2/pub/static/version1518000228/frontend/Magento/luma/en_US/images/loader-1.gif" alt="Loading...">
             </div>
             <div id="zipdata"> </div>
            </div>
        </div>
        
    </div>
</div>



<script type="text/javascript">

    function checkgivenzipcode(){

        require(['jquery', 'jquery/ui'], function($){
		var pinpcode = $('#checkzipcode').val();
        
             if(pinpcode !=''){
                $('#ziploder').show();
                $('#zipdata').html('');  
                $.ajax({
                url : '<?php echo $this->getUrl('zipcodeavailablity/index/zipcheck') ?>',
                data: {"zipcode": pinpcode},
                type: "POST",
                success : function(data) { 
                $('#ziploder').hide(); 
                 $('#zipdata').html(data);            
                }
            }); 
            }
		   

            });
		
	}		
</script>